CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  banned BOOLEAN NOT NULL DEFAULT FALSE,
  avatar_url TEXT,
  bio VARCHAR(500) NOT NULL DEFAULT '',
  theme_color VARCHAR(20) NOT NULL DEFAULT '#159cff',
  theme_mode VARCHAR(10) NOT NULL DEFAULT 'dark',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) NOT NULL DEFAULT '#159cff';
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_mode VARCHAR(10) NOT NULL DEFAULT 'dark';

CREATE TABLE IF NOT EXISTS sessions (
  id CHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS addons (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  category VARCHAR(30) NOT NULL DEFAULT 'Other',
  version VARCHAR(30) NOT NULL DEFAULT '1.0.0',
  filename TEXT NOT NULL,
  original_filename TEXT NOT NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  downloads BIGINT NOT NULL DEFAULT 0,
  likes BIGINT NOT NULL DEFAULT 0,
  cover_image TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE addons ADD COLUMN IF NOT EXISTS cover_image TEXT;
CREATE INDEX IF NOT EXISTS addons_created_idx ON addons(created_at DESC);
CREATE INDEX IF NOT EXISTS addons_category_idx ON addons(category);

CREATE TABLE IF NOT EXISTS addon_images (
  id BIGSERIAL PRIMARY KEY,
  addon_id BIGINT NOT NULL REFERENCES addons(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS addon_likes (
  addon_id BIGINT NOT NULL REFERENCES addons(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (addon_id, user_id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  addon_id BIGINT NOT NULL REFERENCES addons(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (addon_id, user_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGSERIAL PRIMARY KEY,
  addon_id BIGINT NOT NULL REFERENCES addons(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS comments_addon_idx ON comments(addon_id, created_at DESC);


CREATE TABLE IF NOT EXISTS auth_transfers (
  token_hash CHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  return_path TEXT NOT NULL DEFAULT '/',
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS auth_transfers_expiry_idx ON auth_transfers(expires_at);
CREATE INDEX IF NOT EXISTS auth_transfers_user_idx ON auth_transfers(user_id);
